version: '3'
services:
  app:
    image: ghcr.io/webcdc/heroku-discord:latest
    container_name: heroku-to-discord
    environment:
      - DISCORD_WEBHOOK=
      - PORT=3000
    ports:
      - "3000:3000"
    restart: alway